
export const active = {
    ADD : "ADD",
    DELETE: "DELETE",
    INCREMENT_X: "INCREMENT_X",
    DECREMENT_X: "DECREMENT_X",
    INCREMENT_Y: "INCREMENT_Y",
    DECREMENT_Y: "DECREMENT_Y",
    INCREMENT_WIDTH: "INCREMENT_WIDTH",
    DECREMENT_WIDTH: "DECREMENT_WIDTH",
    INCREMENT_HEIGHT: "INCREMENT_HEIGHT",
    DECREMENT_HEIGHT: "DECREMENT_HEIGHT",
}

// export const shape = {
//     Triangle : 'polygon(50% 0%, 0% 100%, 100% 100%);',

// }

